### PR TITLE
Compatibility and deletion of crop images on disk

### PR DESCRIPTION
**Pull request by carlblock**
Hey joppuyo.

Thanks for a great plugin, I been using it in production to replace the old unmaintained crop plugin for acf. Since I have a lot of heavy images on the site I decided to implement the removal of images from the disk when we press the delete button. Since we migrated from the old plugin I decided to have the ability to view the old plugin images in the field also.

**Take a look at it(and test it if you please).** It works fine in _my environment_ but you might encounter new issues. The only missing feature right now is to delete all crop images from disk when the user deletes the post. I might add some pull request for that in the coming weeks.

### CODE REVIEW

**Comment by carlblock** [comment]
I actually found a bug now after the submit, after re-cropping same image and then deleting it removes the previous crop images. I will work on a fix to delete the previous crop images from disk also while re-cropping. And I'll fix the Codacy/PR Quality Review issues.

**Comment by joppuyo** [comment]
Hey! Thanks a lot, looks like really useful functionality.

I'll look through this today.

Don't worry about to Codacy too much, as you might see most of my own code does not pass its checks 😉

**Comment by joppuyo** [comment]
Sorry, I got a bit ahead of myself. By today I mean after you have fixed the bug you encountered

**Comment by carlblock** [comment]
> Sorry, I got a bit ahead of myself. By today I mean after you have fixed the bug you encountered

Hey, thanks! I've made two commits to include the functionality to delete while re-cropping. This won't work retroactively, but only with new crops that are made. Since it's dependent on the post_meta which is created upon cropping. I will do some more testing today and tomorrow to make sure things are working fine!

**Comment by joppuyo** [comment]
Hey! I've given this some thought.

I think compatibility with the older plugin is good and can be added.

But I think there is a better way of implementing removing older images. By hooking into the delete button, you risk deleting some images from a live site while editing a post. For example, if you click the delete button but then don't save the post by navigating to another page in the WordPress admin, the image will be deleted in the live post.

The code also does not take account when the image is re-cropped instead of deleted.

I also think it would make more sense to delete the whole post instead of just the images contained in it, now deleting the cropped image leaves a broken attachment in the database without any images.

I think the best way to address this is something I've thought about in [this issue](https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/4). So I think it would make sense to store something like a "acf_image_aspect_ratio_crop_parent" meta field for each cropped image attachment. Then hook into ACF [save_post](https://www.advancedcustomfields.com/resources/acf-save_post/) action, gather all images related to the current post and delete those images that are not present in the POST request when saving a post.

I think I would have some time to take a look at image deletion myself. So if you want, you could create another pull request for the backward compatibility and I'll merge it.

**Comment by carlblock** [comment]
> Hey! I've given this some thought.
> 
> I think compatibility with the older plugin is good and can be added.
> 
> But I think there is a better way of implementing removing older images. By hooking into the delete button, you risk deleting some images from a live site while editing a post. For example, if you click the delete button but then don't save the post by navigating to another page in the WordPress admin, the image will be deleted in the live post.
> 
> The code also does not take account when the image is re-cropped instead of deleted.
> 
> I also think it would make more sense to delete the whole post instead of just the images contained in it, now deleting the cropped image leaves a broken attachment in the database without any images.
> 
> I think the best way to address this is something I've thought about in [this issue](https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/4). So I think it would make sense to store something like a "acf_image_aspect_ratio_crop_parent" meta field for each cropped image attachment. Then hook into ACF [save_post](https://www.advancedcustomfields.com/resources/acf-save_post/) action, gather all images related to the current post and delete those images that are not present in the POST request when saving a post.
> 
> I think I would have some time to take a look at image deletion myself. So if you want, you could create another pull request for the backward compatibility and I'll merge it.

Hey! I think you're right, I was thinking about that also now that it's probably better to do the deletion on post saving rather than instantaneously after pressing the delete button. I can open a new PR later this week for the backward compatibility.

I'm looking forward to the new image deletion! If you need any help with testing or anything else, just mention @carlblock and I'll try to help you since I appreciate this plugin a lot!

Cheers!

**Pull request closed without merging**
