### PR TITLE
Adding 2 Inputs for manual insert Width and Height in pixels

### PR DESCRIPTION
**Pull request by guytzhak**
Adding 2 input fields to the cropper popup for setting dynamic width and height in pixels when you need specific size manually.

https://prnt.sc/q766m0

### CODE REVIEW

**Comment by guytzhak** [comment]
@joppuyo any update?

**Comment by joppuyo** [comment]
Hey, I don't know if this functionality would fit this plugin since it mixes up the concepts of aspect ratio and pixel size. Users don't really want an image of specific pixels coordinates, they want a specific part of the image.

Here's some discussion about this in this ticket https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/7

Basically the pixel size should be added as on option in the field configuration. If image/selected area is smaller then pixel size, it should be rejected. If it's larger, it should be scaled down to the pixel size.

Unfortunately I'm not sure when I'll be able to look into this since I work on this plugin in my free time and I'm a bit in a rush right now.

**Comment by guytzhak** [comment]
Many users ask me I they can put a specific size to crop.

If user want aspect ration he can insert in the ACF the 3:4 aspect ration and insert specific size in the popup. like 400 width and than the height automatically changed based on the aspect ration.

when No aspect ration inserted, he can know what he want like maybe 768:403 pixels and can put it exactly in the inputs.

Used my patch and see by yourself.

after all - 
It's another way to use the size metter instead of the using with mouse (when click and resize the cropped area) to specific wanted sizes

**Comment by guytzhak** [comment]
You can see in the video: https://drive.google.com/file/d/1URBYebqcdJXfVuh3uO9cjDrFRPmqE-WO/view

**Comment by guytzhak** [comment]
You can see my secondary change for another problem with the thumbnails.

By default on line 333 in the function 'wp_generate_attachment_metadata' in the wordpress core is generating thumbnails. remember(!), this is a cropped image that used in a single place (acf field) and we doesn't need an thumbnails for that so I used this filter to prevent create a thumbnails and this proccess is very quick

**Comment by guytzhak** [comment]
any update?

**Comment by guytzhak** [comment]
Did you add any of my code to the last version?

**Comment by joppuyo** [comment]
Hey, apologies, I completely forgot about this.

Unfortunately, I don't think this PR can be merged as-is. Here are a few comments about several things you have discussed here.

## Text fields to input size as pixels

I don't think this feature is necessary. I can't think about any situation where this might be useful. WordPress admin users don't generally care about the pixel width and height of their image. They just want to select a part of the image that looks good. Pixel width and height is something that the theme and CMS system should manage, not the user.

If you think about the average user, the following train of thought would be really rare:

1. I'm uploading this nice picture to WordPress
2. Hmm, it looks like the system requires the image in aspect ratio 4:3 to display correctly on the site
3. I want the crop to be exactly 640x480px size, I'm going the enter these values into the text box
4. Now I'm satisfied with the values and I press crop

It usually goes more like this:

1. I'm uploading this nice picture to WordPress
2. Hmm, it looks like the system requires the image in aspect ratio 4:3 to display correctly on the site
3. Let me just resize and this move cropper into a position that looks good and does not do something like to crop a person's head out of frame.
4. I'm satisfied with the composition and press crop. The system will handle the rest and I don't have to care about any pixel values

So I think in general this option would be needed. If you can convince me about a use case where this would be necessary we could try to figure out a way to include this in an intuitive way for the user.

## Generating thumbnails for cropped images

In general generating thumbnails is not a bad thing. When you generate thumbnails you can use WordPress's [responsive images](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) functionality. This means that correctly sizes images are served to different platforms like smartphones, tablets, and desktops.

In some rare cases, you might not want to generate these thumbnails and [I plan to add](https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/10) an option to the ACF field settings where you can instead of generating all the thumbnails, whitelist only ones you need.

So an option needs to be added for this instead of a blanket decision to disable thumbnail generation.

**Comment by joppuyo** [comment]
If the theme/CMS needs image in exactly in particular pixel size I have added an option in the latest version to allow this.

You can select "pixel size" in ACF field options instead of "aspect ratio". This will make the minimum image size same as the size you enter, let's say 640x480. Content editor user can select an area of the image they want but it must be 640x480 at the minimum. After cropping is complete if the resulting image is larger than 640x480, it will be scaled down to this resolution.

**Comment by guytzhak** [comment]
Hi, Thanks
I see you last update and he fix this.

another thing is why to display inputs of width/height in the modal?
It's when the user upload images to slider, each page has his own slider and maybe in one page I want 500px height of the slider, but another page I want the slider to be at 300 px height - but I'm using the same ACF Field to manage sldiers.

So in this case I can leave the aspect ration / px size by blank and the user crop by himself the size he want but he can't know the size if he hasn't as the indicators like that.

The new plugin is awesome.

So you plane to whitelist images for generated thumbnails? I can help with that?

**Comment by joppuyo** [comment]
Closing this since I don't think this feature is a good fit for the plugin.

For whitelisting sizes please refer to #10

**Pull request closed without merging**
